name: Auto Update Store

on:
  schedule:
    - cron: '0 0 * * *' # هەموو شەوێک سەعات ١٢ی شەو خۆی ئیش دەکات
  workflow_dispatch: # ڕێگەت پێ دەدات خۆت بە دەستیش ئیشی پێ بکەیت

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Run Updater
        run: python updater.py

      - name: Commit and Push
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add source.json
          git commit -m "Auto update IPA links" || exit 0
          git push
